export enum ParsedInstructionOperation {
  START,
  LOOP,
  INCREMENT_DATA_POINTER,
  DECREMENT_DATA_POINTER,
  INCREMENT_BYTE,
  DECREMENT_BYTE,
  OUTPUT_BYTE,
  INPUT_BYTE,
  MOVE_FORWARD_INSTRUCTION_POINTER,
  MOVE_BACKWARD_INSTRUCTION_POINTER
};